# Generated by Django 5.1.5 on 2025-02-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_alter_bag_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp.bag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='miniapp.bag')),
            ],
        ),
    ]
