# Generated by Django 5.1.5 on 2025-02-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
    ]
